spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cortex
    driverClassName: org.h2.Driver
    username: cortex
    password: cortex
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    config:
      exchange: cortex
      routing-key: cortex.currency
