server:
  port: ${PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:info}
    web: ${LOG_LEVEL_WEB:info}
    org:
      springframework:
        web: ${LOG_LEVEL_SPRING:info}

api:
  bc:
    url: ${API_BC_URL:https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoMoedaDia(moeda=@moeda,dataCotacao=@dataCotacao)}
    conexao:
      timeout: ${API_BC_CONEXAO_TIMEOUT:5}
  cache:
    timeout: ${API_BC_CACHE_TIMEOUT:1}